# Site settings
title: Kwon hye jin
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://poiuyy0420.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kwon hye jin
user_description: 안녕하세요 :)<br> 새로운 기술과 지식에 관심이 많고 소통하는 것을 중요하게 생각하는 Back-end 개발자 입니다.<br><b>Java, Spring MVC, PostgreSQL, Oracle, AWS </b> 기반의 서비스에서 개발 및 운영 경험이 있습니다.<br>하나의 기술과 언어에만 고립되지 않는 개발자로 성장하는 것이 목표입니다.
user_title: Back-end Developer
email: poiuyy0420@naver.com
# twitter_username: poiuyy0420
# github_username:  poiuyy0420
# gplus_username:  poiuyy0420

exclude: ['package.json', 'src' , 'node_modules']
